# Grafana configuration
[security]
admin_user = admin
admin_password = wafa_admin

[auth.anonymous]
enabled = true
org_role = Viewer

[metrics]
enabled = true

[log]
mode = console
level = info

[paths]
provisioning = /etc/grafana/provisioning
