import { Medication, RefillRequest, WeeklyAdherence } from './medication.types';

export const mockMedications: Medication[] = [
  {
    id: '1',
    name: 'Metformin 100mg',
    dosage: '100mg',
    frequency: 'Twice daily, with meals',
    currentStock: 24,
    totalStock: 32,
    unit: 'UNITS',
    status: 'optimal',
    category: 'active',
    iconType: 'pill',
  },
  {
    id: '2',
    name: 'Lisinopril 5mg',
    dosage: '5mg',
    frequency: 'Once daily, morning',
    currentStock: 18,
    totalStock: 30,
    unit: 'UNITS',
    status: 'healthy',
    category: 'active',
    iconType: 'bottle',
  },
  {
    id: '3',
    name: 'Lisinopril 15mg',
    dosage: '15mg',
    frequency: 'Once daily, as needed',
    currentStock: 6,
    totalStock: 30,
    unit: 'UNITS',
    status: 'low',
    category: 'low_stock',
    iconType: 'kit',
  },
  {
    id: '4',
    name: 'Metformin 500mg',
    dosage: '500mg',
    frequency: 'Twice daily, high dose',
    currentStock: 2,
    totalStock: 60,
    unit: 'UNITS',
    status: 'urgent',
    category: 'low_stock',
    iconType: 'urgent_pill',
  },
];

export const mockAdherenceData: WeeklyAdherence[] = [
  { week: 'WEEK 1', taken: 75, missed: 0 },
  { week: 'WEEK 1', taken: 65, missed: 0 },
  { week: 'WEEK 1', taken: 90, missed: 0 },
  { week: 'WEEK 1', taken: 80, missed: 0 },
  { week: 'WEEK 2', taken: 95, missed: 0 },
  { week: 'WEEK 2', taken: 88, missed: 0 },
  { week: 'WEEK 2', taken: 45, missed: 40 },
  { week: 'WEEK 2', taken: 92, missed: 0 },
  { week: 'WEEK 3', taken: 84, missed: 0 },
  { week: 'WEEK 3', taken: 72, missed: 0 },
  { week: 'WEEK 3', taken: 80, missed: 0 },
  { week: 'WEEK 3', taken: 90, missed: 0 },
  { week: 'WEEK 4', taken: 70, missed: 60 },
  { week: 'WEEK 4', taken: 98, missed: 0 },
];

export const mockRefillRequests: RefillRequest[] = [
  {
    id: 'r1',
    medication: 'Metformin 500mg',
    rxNumber: 'Refill #RX-9921',
    pharmacy: 'Walgreens Specialty',
    requestDate: 'May 24, 2024',
    status: 'shipping',
  },
  {
    id: 'r2',
    medication: 'Lisinopril 5mg',
    rxNumber: 'Refill #RX-8842',
    pharmacy: 'CVS Pharmacy',
    requestDate: 'May 12, 2024',
    status: 'completed',
  },
];
